FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG VITE_BASE_API_URL
ARG VITE_APP_NAME
ARG VITE_ALLOWED_HOSTS

ENV VITE_BASE_API_URL=$VITE_BASE_API_URL
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_ALLOWED_HOSTS=$VITE_ALLOWED_HOSTS

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]
