FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG VITE_BASE_API_URL
ARG VITE_STORAGE_URL
ARG VITE_AI_SERVICE_URL
ARG VITE_USE_LARAVEL_AI_GATEWAY
ARG VITE_AI_TIMEOUT_MS
ARG VITE_APP_NAME

ENV VITE_BASE_API_URL=$VITE_BASE_API_URL
ENV VITE_STORAGE_URL=$VITE_STORAGE_URL
ENV VITE_AI_SERVICE_URL=$VITE_AI_SERVICE_URL
ENV VITE_USE_LARAVEL_AI_GATEWAY=$VITE_USE_LARAVEL_AI_GATEWAY
ENV VITE_AI_TIMEOUT_MS=$VITE_AI_TIMEOUT_MS
ENV VITE_APP_NAME=$VITE_APP_NAME

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]
